version: '3'

services:
  back:
    build: .
    container_name: golubator-back
    ports:
      - "8000:8000"
  mongo:
    image: mongo:latest
    container_name: golub-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - golub-mongodb:/data/db

volumes:
  golub-mongodb:
    driver: local
